name: Publish the website
on:
  workflow_dispatch:
  push:
#    branches:
#      - jekyll-site
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Render docs and publish
        run: |
          apt-get install moreutils
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          .github/publish-docs.sh $RELEASE_VERSION
